# Generated by Django 2.2.6 on 2019-11-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191108_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
